### ISSUE TITLE
Browser Control isnt navigating

### ISSUE THREAD

**Issue by carcarjg** [Pocket-PC-Planet/PPCP-AppManager#24]

**Comment by carcarjg** [comment]
May be an issue with the control itself, or it may be how the links are handled.

**Comment by JohnSpahr** [comment]
Very weird. I’d recommend trying to modify how links are handled, and see it that fixes the issue. I’ll (hopefully) be able test it out myself later today

**Comment by carcarjg** [comment]
Welp, Time to track down the source for the webcontrol, as I don't feel like making it from scratch today.

**Comment by carcarjg** [comment]
Was linked to "**appmanager://**" tags. Also doesn't seem to navigate in the WM emulator. _**Works fine on real hardware.**_
