### ISSUE TITLE
Decode # suffixes in links to extract File Name

### ISSUE THREAD

**Issue by carcarjg** [Pocket-PC-Planet/PPCP-AppManager#26]

**Comment by JohnSpahr** [comment]
For now (while we only need to extract file names) this shouldn’t be too difficult, since we can just split the string. I should mention that spaces in the file name are replaced with underscores

**Comment by carcarjg** [comment]
> For now (while we only need to extract file names) this shouldn’t be too difficult, since we can just split the string. 
The way I have it set up it should work with up to 256 "#" arguments. The only issue would be standardizing the format.
IE: <link>#filename#argument2#argument3 or <link>#filename#argument3#argument2
> Quick note: I should mention that spaces in the file name are replaced with underscores
👍

**Comment by carcarjg** [comment]
Implemented. Currently only the file name.
