### ISSUE TITLE
Add archive search tool

### ISSUE THREAD

**Issue by JohnSpahr** [Pocket-PC-Planet/PPCP-AppManager#27]
Title says it all

**Comment by carcarjg** [comment]
Would I take the user search string and put it after the "search_query=". I'm guessing that's what that's there for?

**Comment by carcarjg** [comment]
![image](https://user-images.githubusercontent.com/32466960/101117298-51536900-35ac-11eb-8c52-dd56246c605f.png)
Yep. i'll do that

**Comment by JohnSpahr** [comment]
Yep. It uses ^ symbol as a separator (ex. query^type^category)

**Comment by JohnSpahr** [comment]
Just follow the types and categories found on https://ppcplanet.org/archive

**Comment by carcarjg** [comment]
Implemented.

**Comment by JohnSpahr** [comment]
Excellent! I'll close the issue now.
